# Generated by Django 5.0.6 on 2024-09-07 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Yotoqxona manzili')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha tavsif")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratuvchi vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol yoki nofaol')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dormitory_address_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dormitory_address_updated', to=settings.AUTH_USER_MODEL, verbose_name='Yangilovchi')),
            ],
            options={
                'verbose_name': 'Yotoqxona manzili',
                'verbose_name_plural': 'Yotoqxona manzillari',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Binoning nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Binoning qo'shimcha tavsifi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratuvchi vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol yoki nofaol')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_updated', to=settings.AUTH_USER_MODEL, verbose_name='Yangilovchi')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='e_manzil.dormitoryaddress', verbose_name="Manzilga bog'langan bino")),
            ],
            options={
                'verbose_name': 'Bino',
                'verbose_name_plural': 'Binolar',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Qavat raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratuvchi vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol yoki nofaol')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='e_manzil.building', verbose_name="Binoga bog'langan qavat")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_updated', to=settings.AUTH_USER_MODEL, verbose_name='Yangilovchi')),
            ],
            options={
                'verbose_name': 'Qavat',
                'verbose_name_plural': 'Qavatlar',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Xona raqami')),
                ('capacity', models.PositiveIntegerField(verbose_name='Xonadagi talabalar sig‘imi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratuvchi vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol yoki nofaol')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='e_manzil.floor', verbose_name="Qavatga bog'langan xona")),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_updated', to=settings.AUTH_USER_MODEL, verbose_name='Yangilovchi')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RoomCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_capacity', models.PositiveIntegerField(verbose_name='Xonadagi talabalar sig‘imi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratuvchi vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol yoki nofaol')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_capacity_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_info', to='e_manzil.room', verbose_name="Xonaga bog'langan sig‘im")),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_capacity_updated', to=settings.AUTH_USER_MODEL, verbose_name='Yangilovchi')),
            ],
            options={
                'verbose_name': 'Xona sig‘imi',
                'verbose_name_plural': 'Xona sig‘imlari',
            },
        ),
    ]
