# Generated by Django 5.0.6 on 2024-09-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_manzil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomCapacity',
        ),
    ]
