# Generated by Django 5.0.6 on 2024-10-18 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_manzil', '0002_delete_roomcapacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupants',
            field=models.ManyToManyField(blank=True, related_name='assigned_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Xonadagi talaba yoki hodimlar'),
        ),
    ]
