# Generated by Django 5.0.6 on 2024-09-04 13:42

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Ilmiy daraja kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Ilmiy daraja nomi')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Ilmiy unvon kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Ilmiy unvon nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Talabaning turar joyi kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Talabaning turar joyi nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Fuqarolik kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Fuqarolik nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Mamlakat kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Mamlakat nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeID', models.CharField(max_length=255, verbose_name='Fakultet ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fakultet nomi')),
                ('code', models.CharField(max_length=20, verbose_name='Fakultet kodi')),
                ('parent', models.CharField(blank=True, max_length=20, null=True, verbose_name='Boshqa fakultet')),
                ('active', models.BooleanField(default=True, verbose_name='Faol')),
                ('structure_type', models.CharField(choices=[('10', 'Boshqa'), ('11', 'Fakultet'), ('12', 'Kafedra'), ('13', 'Bo‘lim'), ('14', 'Boshqarma'), ('15', 'Markaz'), ('16', 'Rektorat')], max_length=2, verbose_name='Bo‘lim turi')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Tuman kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Tuman nomi')),
            ],
        ),
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="Ta'lim shakli kodi")),
                ('name', models.CharField(max_length=255, verbose_name="Ta'lim shakli nomi")),
            ],
        ),
        migrations.CreateModel(
            name='EducationLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="Ta'lim tili kodi")),
                ('name', models.CharField(max_length=255, verbose_name="Ta'lim tili nomi")),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="Ta'lim turi kodi")),
                ('name', models.CharField(max_length=255, verbose_name="Ta'lim turi nomi")),
            ],
        ),
        migrations.CreateModel(
            name='EducationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="O'quv yili kodi")),
                ('name', models.CharField(max_length=255, verbose_name="O'quv yili nomi")),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Xodim holati kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Xodim holati nomi')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Xodim turi kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Xodim turi nomi')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Bandlik shakli kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Bandlik shakli nomi')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Bandlik hodimlar kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Bandlik hodimlar nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Jins kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Jins nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Bosqich kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Bosqich nomi')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="To'lov turi")),
                ('name', models.CharField(max_length=255, verbose_name="To'lov nomi")),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Viloyat kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Viloyat nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='role kodi')),
                ('name', models.CharField(max_length=255, verbose_name='role nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Semestr kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Semestr nomi')),
            ],
        ),
        migrations.CreateModel(
            name='SocialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Talaba holati code')),
                ('name', models.CharField(max_length=255, verbose_name='Talaba holati nomi')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="Xodim o'rni kodi")),
                ('name', models.CharField(max_length=255, verbose_name="Xodim o'rni nomi")),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Talabaning holati kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Talabaning holati nomi')),
            ],
        ),
        migrations.CreateModel(
            name='StudentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Talaba turi kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Talaba turi nomi')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_load', models.IntegerField(verbose_name='Akademik yuk')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name="Ta'lim turi kodi")),
                ('name', models.CharField(max_length=255, verbose_name="Ta'lim turi nomi")),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Universitet kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Universitet nomi')),
                ('api_url', models.URLField(blank=True, null=True, verbose_name='API URL')),
                ('api_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Token')),
                ('student_url', models.URLField(blank=True, null=True, verbose_name='Student URL')),
                ('employee_url', models.URLField(blank=True, null=True, verbose_name='Xodimlar URL')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeID', models.CharField(blank=True, max_length=20, null=True, verbose_name="O'quv reja ID")),
                ('name', models.CharField(max_length=255, verbose_name='Dastur nomi')),
                ('semester_count', models.IntegerField(blank=True, null=True, verbose_name='Semestrlar soni')),
                ('education_period', models.IntegerField(blank=True, null=True, verbose_name="Ta'lim davomi (Yilda)")),
                ('educationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.educationform', verbose_name="Ta'lim shakli")),
                ('educationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.educationtype', verbose_name="Ta'lim turi")),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeID', models.CharField(max_length=255, verbose_name="Yo'nalish ID raqami")),
                ('name', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('code', models.CharField(max_length=50, verbose_name="Yo'nalish kodi")),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='Fakultet')),
                ('educationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.educationtype', verbose_name="Ta'lim turi")),
            ],
        ),
        migrations.CreateModel(
            name='GroupUniver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeID', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('name', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Guruh kodi')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.curriculum', verbose_name="O'quv rejasi")),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='Fakultet')),
                ('educationLang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.educationlang', verbose_name="Ta'lim tili")),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialty', verbose_name='Mutaxassislik')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialty', verbose_name="Yo'nalish"),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_acload', models.IntegerField(verbose_name='Umumiy akademik yuk')),
                ('credit', models.IntegerField(blank=True, null=True, verbose_name='Kredit')),
                ('resource_count', models.IntegerField(blank=True, null=True, verbose_name='Resurslar soni')),
                ('in_group', models.IntegerField(blank=True, null=True, verbose_name='Guruhda')),
                ('at_semester', models.BooleanField(blank=True, default=True, null=True, verbose_name='Semestrda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name="Bo'lim")),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.semester', verbose_name='Semestr')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_fan', to='accounts.subject', verbose_name='Fan')),
                ('subjectDetails', models.ManyToManyField(to='accounts.subjectdetail', verbose_name='Fan tafsilotlari')),
            ],
        ),
        migrations.AddField(
            model_name='subjectdetail',
            name='trainingType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainingtype', verbose_name="Ta'lim turi"),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ism")),
                ('short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa ism')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familia')),
                ('third_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan kun")),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='Rasm')),
                ('imageFile', models.ImageField(blank=True, default='default/user.png', null=True, upload_to='students/%Y/%m/%d', verbose_name='Rasmi faylda')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzili')),
                ('year_of_enter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kirish yili')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash')),
                ('now_role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Foydalanuvchining hozirgi vaqtdagi roli')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password_save', models.CharField(blank=True, max_length=128, null=True, verbose_name='password save')),
                ('contractDate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shartnoma sanasi')),
                ('user_type', models.CharField(blank=True, choices=[('1', 'Talaba'), ('2', 'Hodim'), ('3', "O'qituvchi")], default='1', max_length=20, null=True, verbose_name='Type')),
                ('is_student', models.BooleanField(blank=True, default=False, null=True, verbose_name='Talaba')),
                ('is_employee', models.BooleanField(blank=True, default=False, null=True, verbose_name='Hodim')),
                ('is_followers_book', models.BooleanField(default=False, verbose_name='is_followers_book')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('passport_serial', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_jshshir', models.CharField(blank=True, max_length=20, null=True)),
                ('hemis_id', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ID")),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram profil havolasi')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram profil havolasi')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook profil havolasi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('academicDegree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.academicdegree', verbose_name='Ilmiy Daraja')),
                ('academikRank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.academicrank', verbose_name='Ilmiy Unvon')),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accommodation', verbose_name='Turar joyi')),
                ('citizenship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.citizenship', verbose_name='Fuqarolik')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country', verbose_name='Davlat')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.curriculum', verbose_name="O'quv rejasi")),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='Fakultet')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.district', verbose_name='Tuman')),
                ('educationForm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.educationform', verbose_name="Ta'lim shakli")),
                ('educationType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.educationtype', verbose_name="Ta'lim turi")),
                ('educationYear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.educationyear', verbose_name="O'quv yili")),
                ('employeeStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employeestatus', verbose_name='Xodimholati')),
                ('employeeType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employeetype', verbose_name='Xodim turi')),
                ('employmentForm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employmentform', verbose_name='Bandlik shakli')),
                ('employmentStaff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employmentstaff', verbose_name='Bandlik hodimlar')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.gender', verbose_name='Jins')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.groupuniver', verbose_name='Guruh')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.level', verbose_name='Bosqich')),
                ('paymentForm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.paymentform', verbose_name="To'lov turi")),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.province', verbose_name='Viloyat')),
                ('hemis_role', models.ManyToManyField(blank=True, to='accounts.roles', verbose_name='Rollar')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.semester', verbose_name='Semestr')),
                ('socialCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.socialcategory', verbose_name='Talaba Holati')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.specialty', verbose_name='Mutaxassislik')),
                ('staffPosition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffposition', to='accounts.staffposition', verbose_name="Xodimo'rni")),
                ('studentStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentstatus', verbose_name='Talaba holati')),
                ('studentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studenttype', verbose_name='Talaba turi')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.university', verbose_name='Universitet')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
